services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2512
      POSTGRES_DB: employee
    ports:
      - "5410:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker_container
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 2512
      POSTGRES_DB: employee
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

networks:
  redis_postgres_worker_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
