# Imagem base
FROM python:3.10-slim

# Atualiza a lista de pacotes e instala o htop
RUN apt-get update && apt-get install -y htop && rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho
WORKDIR /app

# Copia o código do projeto
COPY worker.py /app/worker.py
COPY requirements.txt /app/requirements.txt

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Executa o script
CMD ["python", "worker.py"]
